/**
 * Created by Evil.01 on 2015/9/6.
 */

var HS_nav= (function(){
    navModule = function ($container_B,data_B) {
        HS_nav.shell.navModule($container_B,data_B)
    };
    return {navModule:navModule}
})();


HS_nav.shell = (function(){
    var navMap = {
        nav_html : [
            '    <div class="navWrap w">',
            '        <div class="navWrap_left fl">',
            '            <ul class="allSub">',
            '                <li>',
            '                    <a class="tit" href="#" class="tit">全部商品分类</a>',
            '                </li>',
            '                <!-- 左侧导航开始 -->',
            '                <div class="w nav_sub">',
            '                    <div class="nav_L">',
            '                        <ul class="nav">',
            '                            <li style="display: block">',
            '                                <dl style="display: block">',
            '                                    <dt>',
            '                                        <div class="tb_l h1"></div>',
                                                     '{{each shunav1.navtitle as value i}}',
            '                                        <a href="{{value.href}}" target="_blank" title="{{value.title}}" class="tb_k">{{value.title}}</a>',
                                                  '{{/each}}',
            '                                        <div class="clear_j"></div>',
            '                                    </dt>',
            '                                    <dd>',
            '{{each shunav1.navcon as value i}}',
            '                                        <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a>',
            '{{/each}}',
            '                                    </dd>',
            '                                </dl>',
            '                                <div class="divWrap">',
            '                                    <span class="divWrapone">',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
            '{{each rightdata1.rightnav1.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
            '{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
            '{{each rightdata1.rightnav1.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',

            '{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata1.rightnav2.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata1.rightnav2.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata1.rightnav3.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}};" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata1.rightnav3.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata1.rightnav4.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata1.rightnav4.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata1.rightnav5.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata1.rightnav5.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata1.rightnav6.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata1.rightnav6.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                    </span>',
            '                                    <span class="divWraptwo">',
            '                                        <p style="height:10px; width:10px; margin:0 auto;"></p>',
            '                                        <p style="margin-left:3px; color:#019002; font-size:14px; font-weight:bold;">推荐品牌</p>',
            '                                        <p style="margin-top:10px;"></p>',
			'{{each rightdata1.tuijian as value i}}',
            '                                        <p style="border:1px solid #eee;float:left; height:74px; padding-top:6px; background:#FFF;"><a href="{{value.href}}" target="_blank" style="padding:0; margin:0;"><img src="{{value.src}}" width="98"></a></p>',
			'{{/each}}',
            '                                        <p style="clear:both;"></p>',
            '                                        <p></p>',
            '                                    </span>',
            '                                    <p style="clear: both"></p>',
            '                                </div>',
            '                            </li>',
            '                            <li style="display: block">',
            '                                <dl style="display: block">',
            '                                    <dt>',
            '                                    <div class="tb_l h1"></div>',
			'{{each shunav2.navtitle as value i}}',
            '                                    <a href="{{value.href}}" target="_blank" title="{{value.title}}" class="tb_k">{{value.title}}</a>',
			'{{/each}}',
            '                                    <div class="clear_j"></div>',
            '                                    </dt>',
            '                                    <dd>',
			'{{each shunav2.navcon as value i}}',
            '                                        <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a>',
			'{{/each}}',
            '                                    </dd>',
            '                                </dl>',
            '                                <div class="divWrap">',
            '                                    <span class="divWrapone">',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav1.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav1.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav2.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav2.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav3.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav3.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav4.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav4.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav5.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="墙地面">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav5.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
			            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav6.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav6.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata2.rightnav7.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata2.rightnav7.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                    </span>',
            '                                    <span class="divWraptwo">',
            '                                        <p style="height:10px; width:10px; margin:0 auto;"></p>',
            '                                        <p style="margin-left:3px; color:#019002; font-size:14px; font-weight:bold;">推荐品牌</p>',
            '                                        <p style="margin-top:10px;"></p>',
			'{{each rightdata2.tuijian as value i}}',
            '                                        <p style="border:1px solid #eee;float:left; height:74px; padding-top:6px; background:#FFF;"><a href="{{value.href}}" target="_blank" style="padding:0; margin:0;"><img src="{{value.src}}" width="98"></a></p>',
			'{{/each}}',
            '                                        <p style="clear:both;"></p>',
            '                                        <p></p>',
            '                                    </span>',
            '                                    <p style="clear: both"></p>',
            '                                </div>',
            '                            </li>',
            '                            <li style="display: block">',
            '                                <dl style="display: block">',
            '                                    <dt>',
            '                                    <div class="tb_l h1"></div>',
			'{{each shunav3.navtitle as value i}}',
            '                                    <a href="{{value.href}}" target="_blank" title="{{value.title}}" class="tb_k">{{value.title}}</a>',
			'{{/each}}',
            '                                    <div class="clear_j"></div>',
            '                                    </dt>',
            '                                    <dd>',
			'{{each shunav3.navcon as value i}}',
            '                                        <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a>',
			'{{/each}}',
            '                                    </dd>',
            '                                </dl>',
            '                                <div class="divWrap">',
            '                                    <span class="divWrapone">',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata3.rightnav1.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata3.rightnav1.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata3.rightnav2.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata3.rightnav2.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata3.rightnav3.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata3.rightnav3.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                        <div class="mt10">',
            '                                            <p class="fl nav_sub3">',
			'{{each rightdata3.rightnav4.navtitle as value i}}',
            '                                                <strong><a href="{{value.href}};" target="_blank" title="{{value.title}}">{{value.title}}</a></strong>',
			'{{/each}}',
            '                                            </p>',
            '                                            <p class="fl nav_sub4">',
			'{{each rightdata3.rightnav4.navcon as value i}}',
            '                                                <a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a><span>|</span>',
			'{{/each}}',
            '                                            </p>',
            '                                        </div>',
            '                                    </span>',
            '                                    <span class="divWraptwo">',
            '                                        <p style="height:10px; width:10px; margin:0 auto;"></p>',
            '                                        <p style="margin-left:3px; color:#019002; font-size:14px; font-weight:bold;">推荐品牌</p>',
            '                                        <p style="margin-top:10px;"></p>',
			'{{each rightdata3.tuijian as value i}}',
            '                                        <p style="border:1px solid #eee;float:left; height:74px; padding-top:6px; background:#FFF;"><a href="{{value.href}}" target="_blank" style="padding:0; margin:0;"><img src="{{value.src}}" width="98"></a></p>',
			'{{/each}}',
            '                                        <p style="clear:both;"></p>',
            '                                        <p></p>',
            '                                    </span>',
            '                                    <p style="clear: both"></p>',
            '                                </div>',
            '                            </li>',
            '                        </ul>',
            '                        <div class="hot_nav">',
            '                            <dl>',
            '                                <dt>',
			'{{each hotarea as value i}}',
            '                                    <span><a href="{{value.href}}" target="_blank" title="{{value.title}}">{{value.title}}</a></span>',
			'{{/each}}',
            '                                </dt>',
            '                            </dl>',
            '                        </div>',
            '                    </div>',

            '                </div>',
            '                <!-- 左侧导航结束 -->',
            '            </ul>',
            '        </div>',
            '        <div class="navWrap_cen fl">',
            '{{each daohang as value i}}'+
            '<a href="{{value.href}}" title="{{value.title}}">{{value.title}}</a>',
            '{{/each}}'+
            '        </div>',
            '        <div class="navWrap_right fr">',
            '            <a href="javascript:;" target="_blank" title="品牌街">品牌街</a>',
            '        </div>',
            '    </div>'].join("")
    };

    navModule = function ($container_B,data_B) {
        navDOM($container_B,data_B);
        navEvent();
        setJqueryMap();
    };
    navDOM = function($container_B,data_B){
        var render = template.compile(navMap.nav_html)
        var html =render(data_B)
        $container_B.append(html);
    };

    navEvent = function(){
		setTimeout(function(){
			 $(".nav_L .nav li").mouseenter(function(){
            $(".divWrap").hide();
            $(this).children(".divWrap").show();
			$(".divWrap").animate({width:790},200);
       		 })
		},500)
       
		 $(".nav_L .nav").mouseleave(function(){
            $(".divWrap").hide().css({width:0});
        })
    };
    return {navModule:navModule}

}());
